### ISSUE TITLE
Initialize tensors by default, and raise dimension mismatch errors.

### ISSUE THREAD

**Issue by kylebd99** [willow-ahrens/Finch.jl#101]
When using the Min function, it seems like Finch gives surprising/incorrect results. For example, the following code:
```
t = @fiber(sl(sl(e(0.0))))
X = @fiber(sl(sl(e(0.0))))
A = copyto!(@fiber(sl(sl(e(0.0)))), SparseMatrixCSC([0 0 0 0; -1 -1 -1 -1; -2 -2 -2 -2; -3 -3 -3 -3]))
@finch @loop i j t[i, j] = min(A[i, j],  X[i, j])
```
Results in the correct output for t:
```
SparseList (0.0) [1:4]
│ 
├─[1]:
│ SparseList (0.0) [1:4]
│ │ 
│ └─[1] [2] [3] [4]
│   0.0 0.0 0.0 0.0
│ 
├─[2]:
│ SparseList (0.0) [1:4]
│ │ 
│ └─[1]  [2]  [3]  [4] 
│   -1.0 -1.0 -1.0 -1.0
│ 
├─[3]:
│ SparseList (0.0) [1:4]
│ │ 
│ └─[1]  [2]  [3]  [4] 
│   -2.0 -2.0 -2.0 -2.0
│ 
├─[4]:
│ SparseList (0.0) [1:4]
│ │ 
│ └─[1]  [2]  [3]  [4] 
│   -3.0 -3.0 -3.0 -3.0
```
However, when I switch the arguments, it changes the output.
```
t = @fiber(sl(sl(e(0.0))))
X = @fiber(sl(sl(e(0.0))))
A = copyto!(@fiber(sl(sl(e(0.0)))), SparseMatrixCSC([0 0 0 0; -1 -1 -1 -1; -2 -2 -2 -2; -3 -3 -3 -3]))
@finch @loop i j t[i, j] = min(X[i, j],  A[i, j])
```
Results in an empty/all zeros tensor for t.
```
SparseList (0.0) [1:0]
│ 
```
Note: This order-dependent behavior also occurs when using positive values for A and max instead of min.

**Comment by kylebd99** [comment]
Note: This behavior goes away when X is explicitly copied from a sparse matrix, so maybe this is about initialization? The following returns correct results.
```
t = @fiber(sl(sl(e(0.0))))
X = copyto!(@fiber(sl(sl(e(0.0)))), SparseMatrixCSC([0 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0]))
A = copyto!(@fiber(sl(sl(e(0.0)))), SparseMatrixCSC([0 0 0 0; 1 1 1 1; 2 2 2 2; 3 3 3 3]))
@finch @loop i j t[i, j] = max(X[i, j],  A[i, j])
```

**Comment by willow-ahrens** [comment]
That would make sense, the kernel code is the same up to renaming. Currently, creating a tensor with `Fiber` or `@fiber` produces a size-zero tensor with potentially uninitialized state, and dimension checking is turned off.

**Comment by willow-ahrens** [comment]
I'm working on an update to the level formats that always initializes the fibers, and I'll add dimension checking to https://github.com/willow-ahrens/Finch.jl/issues/97.

In any event, I'll add this kernel to the test suite to make sure it works.

**Comment by willow-ahrens** [comment]
All done! Tensors are now initialized by default, and dimensions are checked.
