### ISSUE TITLE
Document Syntax for Custom Reduction Operators and Tensor Reuse Errors

### ISSUE THREAD

**Issue by kylebd99** [willow-ahrens/Finch.jl#102]
This may already be available, and if so I'll move this to the documentation issue instead. But, it would be helpful for some applications to be able to take the min/max over some set of dimensions similarly to the += functionality.

For example, this is a somewhat ugly proposed interface:
```
@finch @loop i j C[i] min= A[i j] * B[j]
```

I attempted the following workaround which compiles, but doesn't produce consistent results. For instance,
```
C = @fiber(sl(4, e(-Inf)))
B = dropdefaults(copyto!(@fiber(sl(e(0.0))), SparseMatrixCSC([4 4 4 4])))
A = dropdefaults(copyto!(@fiber(sl(sl(e(0.0)))), SparseMatrixCSC([3 3 3 5; 2 2 2 6; 1 1 1 7; 0 0 0 10])))
@finch @loop i j t[i] = max(t[i], A[i, j] * B[j])
```
Results in the following incorrect result:
```
SparseList (0.0) [1:4]
│ 
└─[1]  [2] [3]
  12.0 8.0 4.0
```

I think this is again due to the dimensionality where t is implicitly viewed as having dimension of length 1 in j. If we change the first value of the j index, this changes the output which supports this conclusion.For instance,
```
C = @fiber(sl(4, e(-Inf)))
B = dropdefaults(copyto!(@fiber(sl(e(0.0))), SparseMatrixCSC([4 4 4 4])))
A = dropdefaults(copyto!(@fiber(sl(sl(e(0.0)))), SparseMatrixCSC([10 3 3 5; 10 2 2 6; 10 1 1 7; 10 0 0 10])))
@finch @loop i j t[i] = max(t[i], A[i, j] * B[j])
```
Results in the following result:
```
SparseList (0.0) [1:4]
│ 
└─[1]  [2]  [3]  [4] 
  40.0 40.0 40.0 40.0
```

**Comment by willow-ahrens** [comment]
Yes, there is a syntax for this and it's even less beautiful than what you suggest!

You can do `@finch @loop i j t[i] <<max>>= A[i, j] * B[j]` to use a custom reduction.

I think an error should have been raised saying that it's not valid to use a tensor on the right and left hand side.

**Comment by willow-ahrens** [comment]
(There's a somewhat complicated calculus for when it's okay to use the result of a temporary, and it has to do with the where statements, but I'm working on a different language with equivalent functionality that makes this easier to explain.)

**Comment by kylebd99** [comment]
Ahh, this is perfect! I'll add an error message request to that thread. Also, the database community has been separately trying to describe when recursion and aggregates work together sensibly, and it's definitely complicated. See [here](https://arxiv.org/pdf/2202.10390.pdf).

**Comment by willow-ahrens** [comment]
I'm going to rename based on the remaining issues in this discussion, if you don't mind.

**Comment by kylebd99** [comment]
Sounds good! I just attempted the custom reduction syntax, and it doesn't give the results that I would expect.
```
C = @fiber(sl(e(0.0)))
B = copyto!(@fiber(sl(e(0.0))), SparseMatrixCSC([1 1 1 1]))
A = copyto!(@fiber(sl(sl(e(0.0)))), SparseMatrixCSC([1 1 1 1; 1 1 1 1; 1 1 1 1; 1 1 1 1]))
@finch @loop i j C[i] <<max>>= A[i, j] * B[i]
```
This results in the following C:
```
SparseList (0.0) [1:4]
│ 
└─[1] [2] [3] [4]
  1.0 0.0 0.0 0.0
```
Without the multiplication with B[i] or if you instead multiply with B[j], it results in the correct vector of all 1s. In general, reduction over a single tensor seems to work:
```
C = @fiber(sl(e(0.0)))
A = copyto!(@fiber(sl(sl(e(0.0)))), SparseMatrixCSC([1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 16]))
@finch @loop i j C[i] <<max>>= A[i, j]
```
Results in [4 8 12 16] like you would expect.

---------------------------------------------------------------------

Attempting the same with addition results in strange behavior as well...
```
C = @fiber(sl(e(0.0)))
B = copyto!(@fiber(sl(e(0.0))), SparseMatrixCSC([1 1 1 1]))
A = copyto!(@fiber(sl(sl(e(0.0)))), SparseMatrixCSC([1 1 1 1; 1 1 1 1; 1 1 1 1; 1 1 1 1]))
@finch @loop i j C[i] += A[i, j] * B[j]
```
This results in [1 1 1 1] rather than [4 4 4 4] which I would expect. Additionally, if you switch B[j] to B[i], it results in [4 0 0 0].

If B is removed from the equation entirely, it produces the correct result of [4 4 4 4].

**Comment by willow-ahrens** [comment]
Okay, this is really subtle, but this is another dimension mismatch error due to trying to convert B from a column vector. 

```
julia> size([1 1 1 1])
(1, 4)

julia> size(copyto!(@fiber(sl(e(0.0))), [1 1 1 1]))
(1,)

 julia> size(copyto!(@fiber(sl(e(0.0))), [1, 1, 1, 1]))
(4,)

julia> A = copyto!(@fiber(sl(sl(e(0.0)))), SparseMatrixCSC([1 1 1 1; 1 1 1 1; 1 1 1 1; 1 1 1 1]));

julia> B = copyto!(@fiber(sl(e(0.0))), [1, 1, 1, 1])
SparseList (0.0) [1:4]
│ 
└─[1] [2] [3] [4]
  1.0 1.0 1.0 1.0

julia> C = @fiber(sl(e(0.0)));

julia> @finch @loop i j C[i] <<max>>= A[i, j] * B[i];-

julia> C
SparseList (0.0) [1:4]
│ 
└─[1] [2] [3] [4]
  1.0 1.0 1.0 1.0
```

**Comment by willow-ahrens** [comment]
In short, row vectors (created by separating with spaces) are two dimensional, and so the second prompt really should have errored due to a mismatch in the number of dimensions.

**Comment by willow-ahrens** [comment]
Julia is Column major, which presents a few issues because finch is currently row-major to express similarity between loop order and binding order. See issue https://github.com/willow-ahrens/Finch.jl/issues/92

**Comment by kylebd99** [comment]
Ahh, this makes a lot of sense now. Thanks for the explanation!
