### ISSUE TITLE
Add simplified interface to custom ops

### ISSUE THREAD

**Issue by willow-ahrens** [willow-ahrens/Finch.jl#29]
some operations to consider: or, logical_or, min, choose, max

It would really help to write rules using declared properties like `isassociative(f)` or `isidempotent(f)`

**Comment by Wimmerer** [comment]
What properties does Finch notionally work with? Associativity, idempotency, commutativity? Some notion of default identity.

SuiteSparseGraphBLAS also uses annihilation for early reduction stopping.

**Comment by willow-ahrens** [comment]
The big question Finch wants to answer is whether we can shortcut f(a, b) -> ?, for various values of f and a and b. We currently add rewrite rules which say things like "+(a, 0) -> a". This is great if you are comfortable writing rewrite rules, but we would like to make this easier for users.

The big additions would be

`iszerolike(f, g, z)` which means `f(a..., z, b...) -> f(a..., b...)` and `g(a..., z, b...) -> z`
`isonelike(g, z)` which means `g(a..., z, b...) -> g(a..., b...)`
`isassociative(f)` and `iscommutative(f)` help a lot with constant propagation `f(1, a, 2) -> f(f(1, 2), a)` kinda stuff.
`isdistributive(f)` is good for simplifying some rare loops.
`ispure(f)` this is just assumed, I think it should default true.
`isidempotent(f)` is good for `f(a, a, a) -> a`, which shows up when `f=min`.

This file https://github.com/willow-ahrens/Finch.jl/blob/main/src/annihilate.jl has all of the rewrite rules that constitute annihilation in Finch, and we should be able to use the above functions to generalize most of them.

**Comment by willow-ahrens** [comment]
Consider the ongoing rewrite to add these properties in https://github.com/willow-ahrens/Finch.jl/blob/a846557b662033808d5b3af6661618c3e8a10fb2/src/annihilate.jl

Do you think there's a cleaner way to do inverses or distributed properties?
If we frame all of our properties as e.g. `isinverse(+, -) = true`, it doesn't give us the info we need to ask for the inverse of +.
We kinda want to have all directions of `getinverse(+) = -`, `getoperator(-) = +`, `isinverse(+, -) = true`.
same goes for identities and annihilators (e.g. `isannihilator` vs. `getannihilator`).
