### ISSUE TITLE
getroot() function

### ISSUE THREAD

**Issue by hochawa** [willow-ahrens/Finch.jl#317]
It is possible that a bug exists within the getroot() function, as evidenced in the Finch code below. Specifically, in the k2 loop, only tensor B appears to be detected in the variable "used_in_scope".

@finch_code begin
        B0 .= 0
        C .= 0
  for i0=_
        B0[i0] = A0[i0]
        for i=gpublock_parallel(_), j=_
                for k=gputhread_parallel(_)
                        C[j,i] += A[k,i] * B[j,k]
                end
                for k2=gputhread_parallel(_)
                        D[j,i] += A[k2,i] * B[j,k2]
                end
        end
  end
end

Here are the outputs of getroot() regarding the Finch code above.

getroot(
virtual(Finch.VirtualScalar(nothing, Float64, 0.0, Symbol("##323"), :(D_lvl_2_val[D_lvl_2_q])))
) -> nothing
getroot(
virtual(Finch.Furlable(Finch.var"#1138#1141"{Finch.DenseTraversal, Finch.FinchNotation.Reader, Vector{typeof(Finch.FinchNotation.defaultread)}, Symbol, DataType, Finch.FinchNotation.FinchNode, Finch.VirtualDenseLevel}(Finch.DenseTraversal(Finch.VirtualSubFiber{Finch.VirtualDenseLevel}(Finch.VirtualDenseLevel(Finch.VirtualElementLevel(:A_lvl_3, 0.0, Float64, Int64, :A_lvl_2_val), :A_lvl_2, Int64, value(A_lvl_2.shape, Int64)), value(A_lvl_q_2, Int64)), Finch.VirtualSubFiber), Finch.FinchNotation.Reader(), typeof(Finch.FinchNotation.defaultread)[], :A_lvl_2_q_2, Int64, value(A_lvl_q_2, Int64), Finch.VirtualDenseLevel(Finch.VirtualElementLevel(:A_lvl_3, 0.0, Float64, Int64, :A_lvl_2_val), :A_lvl_2, Int64, value(A_lvl_2.shape, Int64)))))
) -> nothing
getroot(
virtual(Unfurled(variable(B), 0, Unfurled(Finch.VirtualFiber{Finch.VirtualDenseLevel}(Finch.VirtualDenseLevel(Finch.VirtualDenseLevel(Finch.VirtualElementLevel(:B_lvl_3, 0.0, Float64, Int64, :B_lvl_2_val), :B_lvl_2, Int64, value(B_lvl_2.shape, Int64)), :B_lvl, Int64, value(B_lvl.shape, Int64))), 0, Finch.Furlable(Finch.var"#1138#1141"{Finch.DenseTraversal, Finch.FinchNotation.Reader, Vector{typeof(Finch.FinchNotation.defaultread)}, Symbol, DataType, Finch.FinchNotation.FinchNode, Finch.VirtualDenseLevel}(Finch.DenseTraversal(Finch.VirtualSubFiber{Finch.VirtualDenseLevel}(Finch.VirtualDenseLevel(Finch.VirtualDenseLevel(Finch.VirtualElementLevel(:B_lvl_3, 0.0, Float64, Int64, :B_lvl_2_val), :B_lvl_2, Int64, value(B_lvl_2.shape, Int64)), :B_lvl, Int64, value(B_lvl.shape, Int64)), literal(1)), Finch.VirtualSubFiber), Finch.FinchNotation.Reader(), [Finch.FinchNotation.defaultread], :B_lvl_q_2, Int64, literal(1), Finch.VirtualDenseLevel(Finch.VirtualDenseLevel(Finch.VirtualElementLevel(:B_lvl_3, 0.0, Float64, Int64, :B_lvl_2_val), :B_lvl_2, Int64, value(B_lvl_2.shape, Int64)), :B_lvl, Int64, value(B_lvl.shape, Int64)))))))
) -> variable(B)

I traced the above outputs with this code:

used_in_scope = unique(filter(!isnothing, map(node-> begin
        if @capture(node, access(~tns, ~mode, ~idxs...))
            println("- -")
            println(tns)
            println(getroot(tns))
            println("- -")
            getroot(tns)
        end
    end, PostOrderDFS(root.body))))

Additionally, the malfunctioning of the ensure_concurrent() function appears to be linked to the incorporation of getroot() within it.

**Comment by willow-ahrens** [comment]
The unfurled node was meant to preserve information about the tensor root, even when we are looking at a slice of the tensor. However, they have been added to the system in an ad-hoc way, so they sometimes aren't inserted properly, and it's not always clear when they are needed. This is one of the side effects of wrapper arrays, etc. The Unfurled node was meant to add size and root information to the looplet struct types, but I wonder if it could be done more systematically.

**Comment by willow-ahrens** [comment]
@changwan I think I'm gonna need a smaller reproducing example? could you post a working MRE (Minimum Reproducing Example)?

**Comment by willow-ahrens** [comment]
@finch_code begin
       B .= 0
       for i=_, j=parallel(_)
           B[j,i] += A[j, i]
       end
       end
