### ISSUE TITLE
Kernelize Intermediate Finch Code

### ISSUE THREAD

**Issue by wraith1995** [willow-ahrens/Finch.jl#347]
Add Changwan to this when he accepts the repo invite.

To launch GPU kernels, we need to do the following when we lower a gpu parallel loop:

1. Generate the Julia code
2. Find all the variables in the Julia code that are defined in the Julia code above - roughly all the free variables.
3. Wrap the code into a function with these variables as arguments. Place the function at the top of the program.
4. Call the function.

I think this requires two new things:

1. A top of program preamble available in all contexts.
2. A tool to find the free variables in our generated code at some intermediate step of code generation.

**Comment by willow-ahrens** [comment]
it looks like julia gpu might just be able to handle a closure, in which case:

https://github.com/JuliaGPU/CUDA.jl/issues/67
and
https://github.com/JuliaGPU/CUDA.jl/pull/625

seem to indicate that simply using a closure will work. If that's the case, we may not need to roll our own free variable analysis, julia would do it for us and Cuda.jl would inspect the resulting closure fields for the closed upon variables

**Comment by willow-ahrens** [comment]
Until we have a test that indicates closures won't work, I think we should probably apply the wontfix label here. Feel free to reopen if this becomes a blocker.
