### ISSUE TITLE
CUDA.JL style atomics

### ISSUE THREAD

**Issue by wraith1995** [willow-ahrens/Finch.jl#398]
After #246 is finished via an atomic level, we should add another atomics type via the way CUDA.JL handles atomics. We can simply use their code and make it an optional dependency.

**Comment by willow-ahrens** [comment]
could you help clarify what's missing from atomic PR?

**Comment by wraith1995** [comment]
the `get_lock` function for standard atomics should be implemented via the functions found [here](https://github.com/JuliaGPU/CUDA.jl/blob/4537bc03fedc5239bf314dd307623814dd879c75/src/device/intrinsics/atomics.jl#L8).

**Comment by willow-ahrens** [comment]
Okay, yes we could add CUDA as an optional dependency. I would defer this issue until we have a demonstrated performance problem from the locks we already have though.
