### ISSUE TITLE
Clean up make_lock

### ISSUE THREAD

**Issue by wraith1995** [willow-ahrens/Finch.jl#400]
Currently make_lock and the management of arrays of locks is a bit messy/nonsensical. We need a semantics that deals with SpinLock and the case where we can just use raw data.

**Comment by willow-ahrens** [comment]
I think it should be fine to simply delete the if statements and breaks in https://github.com/willow-ahrens/Finch.jl/blob/f26f14706fe4485e69b9a198fcbff770c0de6413/src/tensors/levels/atomiclevel.jl#L138C1-L140C21
