### ISSUE TITLE
Copying in `Tensor(lvl, arr)` constructor

### ISSUE THREAD

**Issue by mtsokol** [willow-ahrens/Finch.jl#403]
Hi @willow-ahrens,

I started working on zero-copy fully dense Finch Tensor support, and I noticed that there might be a copy created already in the Finch's Tensor constructor (or juliacall when passing an NumPy object?). 

Here's a code that shows it:
```python
import numpy as np
import juliapkg
juliapkg.add("Finch", "9177782c-1635-4eb9-9bfb-d9dfa25e6bce", version="0.6.10")
import juliacall
juliapkg.resolve()
from juliacall import Main as jl
jl.seval("using Finch")

arr = np.arange(24)
t = jl.Tensor(jl.Dense(jl.Element(0)), arr)

assert np.shares_memory(arr, arr)
assert np.shares_memory(t.lvl.lvl.val, t.lvl.lvl.val)
assert np.shares_memory(arr, t.lvl.lvl.val) # <-- error
```

I think that the Tensor constructor:
```julia
Tensor(lvl::AbstractLevel, arr) = dropdefaults!(Tensor(lvl), arr)
```
uses `function dropdefaults_helper!` which potentially might always create a copy?

**Comment by willow-ahrens** [comment]
The `Tensor(arr)` constructor is sometimes non-copying (in julia, we can't do non-copying reshapes without some gymnastics so I've left it out), but when you do `Tensor(lvl, arr)`, you have already allocated the level storage you want to put `arr` into so it copies. In this case, you should construct the dense levels directly, so `Tensor(arr::np.Array)` should construct something like `jl.Tensor(jl.Dense(jl.Dense(jl.Dense(jl.Element(0, np.reshape(arr, np.size(arr)))))))`

**Comment by mtsokol** [comment]
@willow-ahrens Thank you, it works for me! With `t = jl.Tensor(jl.Dense(jl.Element(0, arr), 24))` the last check passes.
