### ISSUE TITLE
Wrapping `SwizzleArray` in `LazyTensor` fails

### ISSUE THREAD

**Issue by mtsokol** [willow-ahrens/Finch.jl#457]
Hi @willow-ahrens,

Then passing `SwizzleArray` to `LazyTensor` constructor, to create a lazy object:
```julia
A = zeros(Int64, (2, 4))
A_tns = Tensor(Dense(Dense(Element(0))), A)
A_sw = Finch.SwizzleArray(A_tns, 1, 2)
Finch.LazyTensor(A_sw)
```
I get an error:
```
ERROR: MethodError: no method matching Finch.LazyTensor(::Finch.SwizzleArray{(1, 2), Tensor{DenseLevel{Int64, DenseLevel{Int64, ElementLevel{…}}}}})

Closest candidates are:
  Finch.LazyTensor(::Finch.LazyTensor)
   @ Finch ~/JuliaProjects/Finch.jl/src/interface/lazy.jl:39
  Finch.LazyTensor(::Number)
   @ Finch ~/JuliaProjects/Finch.jl/src/interface/lazy.jl:21
  Finch.LazyTensor(::Tensor)
   @ Finch ~/JuliaProjects/Finch.jl/src/interface/lazy.jl:31
  ...
```

**Comment by willow-ahrens** [comment]
Could you push a fix for this? We just need to convert the underlying tensor to a LazyTensor `A`, then permute the extrude field
```
B.extrude = A.extrude[dims]
```
and wrap the query in the appropriate reordering 
```
idxs = [field(Symbol(:i_, n)) for n = 1:N]; 
B.data = reorder(relabel(A.data, idxs...), idxs[dims]...)
```

**Comment by willow-ahrens** [comment]
incidentally, this is also how we would support permutedims(Tensor) and swizzle(lazyTensor)

**Comment by willow-ahrens** [comment]
If you want, your PR could also add support for permutedims in the `eager.jl` file by converting to lazy, permuting dims, and converting back.

**Comment by mtsokol** [comment]
Sure! I will work on this on Monday.
