### ISSUE TITLE
Error about Lexicographical order

### ISSUE THREAD

**Issue by adadima** [willow-ahrens/Finch.jl#51]
Happens on statement: 

`@finch @loop j i B[i] <<min>>= edges[j,i] * old_ids[j] + (1 - edges[j,i]) * old_ids[i]`

Error message:
```
RewriteTools.RuleRewriteError((Finch.IndexNotation.call)(min, a...) => if !(issorted(a, by = Lexicography))
        #= /Users/adadima/mit/commit/Finch.jl/src/annihilate.jl:49 =#
        (Finch.IndexNotation.call)(min, sort(a, by = Lexicography)...)
    end, call(min, access(Finch.VirtualFiber{Finch.VirtualDenseLevel}(Finch.VirtualDenseLevel(:B_lvl, Int32, Virtual{Int64}(:(B_lvl.I)), Finch.VirtualElementLevel(:B_lvl_2, Int32, 2147483647, :B_lvl_2_val_alloc, :B_lvl_2_val)), Finch.VirtualEnvironment(Dict{Symbol, Any}(:name => Literal{Symbol}(:B)))), Read(), Name(:i)), access(Finch.VirtualFiber{Finch.VirtualDenseLevel}(Finch.VirtualDenseLevel(:old_ids_lvl, Int32, Virtual{Int64}(:(old_ids_lvl.I)), Finch.VirtualElementLevel(:old_ids_lvl_2, Int32, 0, :old_ids_lvl_2_val_alloc, :old_ids_lvl_2_val)), Finch.VirtualEnvironment(Dict{Symbol, Any}(:name => Literal{Symbol}(:old_ids)))), Read(), Name(:i))))

caused by: MethodError: no method matching priority(::Finch.VirtualFiber{Finch.VirtualDenseLevel})
Closest candidates are:
  priority(::Number) at ~/mit/commit/Finch.jl/src/IndexNotation/nodes.jl:429
  priority(::Function) at ~/mit/commit/Finch.jl/src/IndexNotation/nodes.jl:432
  priority(::Literal) at ~/mit/commit/Finch.jl/src/IndexNotation/nodes.jl:444
```

**Comment by willow-ahrens** [comment]
@adadima I'm having trouble reproducing, could you also give the formats for the tensors?

**Comment by adadima** [comment]
Sure, I was thinking maybe I am using the new Dense level wrong, since that's one of the things I had to change to integrate the new Finch. Here's the tensors:

`jl_value_t* B = Finch.Fiber(
        Dense(N,
            Element{val, Cint}([])
        )
    )
`

`jl_value_t* edges = finch_Fiber(
        finch_DenseLevel(finch_Cint(N),
                finch_DenseLevel(finch_Cint(N),
                    finch_ElementLevel(finch_Cint(0), edge_vector)
                )
            )
        );
`

`jl_value_t* old_ids = finch_Fiber(
        finch_DenseLevel(finch_Cint(N),
        finch_ElementLevel(finch_Cint(0), finch_eval("Cint[]")))
    );
`

**Comment by willow-ahrens** [comment]
I still can't reproduce, I'm not quite sure what's going on? I will try it with the C interface later.
