### ISSUE TITLE
Issue with Colon indexing in 1D arrays

### ISSUE THREAD

**Issue by mtsokol** [willow-ahrens/Finch.jl#527]
Hi @willow-ahrens,

I started working on supporting `None`, and `:` fully in indexing. Here's one issue that I found:

```julia
using Finch

tns_1 = swizzle(Tensor(ones(10, 10)), 1, 2)
tns_1[:, :]  # works

tns_2 = swizzle(Tensor(ones(10)), 1)
tns_2[:]  # fails
```

**Comment by willow-ahrens** [comment]
I think the best approach to fixing this issue is to move dimension expansion to a separate function. That said, I'll push a fix to this too.
