### ISSUE TITLE
Lazy indexing - issue with the rightmost `nothing` dimension

### ISSUE THREAD

**Issue by mtsokol** [willow-ahrens/Finch.jl#528]
Hi @willow-ahrens,

While implementing lazy indexing for SDDMM I noticed that adding a new singleton dimension to the rightmost position fails (which is needed for lazy indexing version of SDDMM):

```julia
using Finch

tns = swizzle(Tensor(ones(10, 10)), 1, 2)
tns[:, :]
tns[nothing, :, :]
tns[:, nothing, :]
tns[:, :, nothing]  # fails
```

**Comment by willow-ahrens** [comment]
mateusz, do you mind if we call this function expand_dims like it's called in python?

**Comment by willow-ahrens** [comment]
Trying to get everything to all fit inside getindex is a lot of overhead

**Comment by willow-ahrens** [comment]
I've pushed a Pr to fix it, and I'll rename the functionality in a separate PR later (this evening perhaps, it's not as urgent as fixing the problem). I think the indexing is both lazy and eager.

**Comment by willow-ahrens** [comment]
do you need a new version?

**Comment by mtsokol** [comment]
Yes please!
