### ISSUE TITLE
SDDMM speedup goal

### ISSUE THREAD

**Issue by willow-ahrens** [willow-ahrens/Finch.jl#538]
Lets get a real speedup in https://github.com/pydata/sparse/pull/674

**Comment by mtsokol** [comment]
@willow-ahrens We merged https://github.com/pydata/sparse/pull/674 and with Finch `v0.6.26` we have x2.5 speedup (It's still away from x100) for NxN arrays where N=10000 and density is 0.0001 compared to both Numba and SciPy! :tada:

**Comment by willow-ahrens** [comment]
Finch
Took 0.009948968887329102 s.

Numba
Took 0.44066866238911945 s.

SciPy
Took 0.2068446477254232 s.

**Comment by mtsokol** [comment]
Wow! This looks amazing!

Did you change any parameters/code in https://github.com/pydata/sparse/blob/main/examples/sddmm_example.py?

**Comment by willow-ahrens** [comment]
https://gist.github.com/willow-ahrens/94f35177fa163cc78ed3d0242b6051ef

**Comment by willow-ahrens** [comment]
I changed some of the code. The issue right now is that the performance of dense matmul is pretty good.

**Comment by willow-ahrens** [comment]
this is a 43x improvement, is this good enough?

**Comment by mtsokol** [comment]
x43 is what we needed for sure! Thank you!!!
