### ISSUE TITLE
support non-boolean dtypes in `any` and `all`

### ISSUE THREAD

**Issue by mtsokol** [willow-ahrens/Finch.jl#575]
Hi @willow-ahrens,

Here's one detail for `any` and `all`. To adhere to Array API we should also support other dtypes (int, float). One option is: I can do it on `finch-tensor` side where I call eager `astype(tns, finch.bool)` to convert to bool, but then we still need support converting non-bool to bool dtypes in Finch. Or support all dtypes in `any`, `all` directly. 
I'm not sure what is the correct way.

**Comment by willow-ahrens** [comment]
Ah yes, this is a little strange because julia doesn't have a default notion of truthyness. At some point we may want to start defining some python-specific operators in finch-tensor for this kind of thing. However, in this case, could we map "!iszero" or `!= 0` before `any`?

**Comment by mtsokol** [comment]
Sure! I will do it this way.

**Comment by willow-ahrens** [comment]
Okay, I'll close this issue then if that's alright?

**Comment by mtsokol** [comment]
Sure! I will reach out if `!= 0` won't be sufficient.
