### ISSUE TITLE
`floor_div` mixed dtypes

### ISSUE THREAD

**Issue by mtsokol** [willow-ahrens/Finch.jl#592]
Hi @willow-ahrens,

One of the `array-api-tests` failures is caused by returning abstract dtypes instead of concrete ones in `floor_div` for mixed data types. The lower one should be promoted to the larger size ([rules](https://data-apis.org/array-api/latest/API_specification/type_promotion.html#rules)):

```julia
julia> using Finch

julia> eltype(broadcast(Finch.fld_nothrow, Tensor(ones(Int16, 1)), Tensor(ones(Int8, 1))))
┌ Warning: Division by zero in fld
└ @ Finch ~/JuliaProjects/Finch.jl/src/util/special_functions.jl:125
Signed

julia> eltype(broadcast(Finch.fld_nothrow, Tensor(ones(Float64, 1)), Tensor(ones(Float32, 1))))
┌ Warning: Division by zero in fld
└ @ Finch ~/JuliaProjects/Finch.jl/src/util/special_functions.jl:125
┌ Warning: Division by zero in fld
└ @ Finch ~/JuliaProjects/Finch.jl/src/util/special_functions.jl:125
┌ Warning: Division by zero in fld
└ @ Finch ~/JuliaProjects/Finch.jl/src/util/special_functions.jl:125
AbstractFloat
```

**Comment by willow-ahrens** [comment]
oh, strange. You're right, this should return Float64. I'll look into it.

**Comment by mtsokol** [comment]
Thank you! For `Int16` and `Int8` it should return `Int16` according to promotion rules.

**Comment by willow-ahrens** [comment]
ah, I see. The issue is actually in the definition.
```
"""
    fld_nothrow(x, y)

Returns `fld(x, y)` normally, returns zero and issues a warning if `y` is zero.
"""
fld_nothrow(x, y) = iszero(y) ? (@warn("Division by zero in fld"); zero(y)) : fld(x, y)
```
This definition returns Float32 or Float64 depending on whether y is zero

**Comment by willow-ahrens** [comment]
should be a quick fix.

**Comment by willow-ahrens** [comment]
I'll fix the floor-div functions, but also note:

The return type of Finch high-level interface is currently based on:

https://github.com/JuliaLang/julia/blob/46933b8a708453f9caecb8abce88770c4bff675d/base/promotion.jl#L508-L619

We may want to provide an interface inside Finch or otherwise which the user can directly modify to ensure predictable output types.
