### ISSUE TITLE
Copying swizzles

### ISSUE THREAD

**Issue by mtsokol** [willow-ahrens/Finch.jl#609]
Hi @willow-ahrens,

I'm writing with one question regarding `Tensor` and `SwizzleArray`. 

When I want to convert one format to another we have:
```python
jl.swizzle(
    jl.Tensor(storage.levels_descr._obj, tensor._obj.body), *order
)
```
Which copies Tensor to the new format (and discards order of unwrapped `tensor` and sets `order`). This requires that `order` argument matches `tensors`'s order.

I can also pass `tensor`'s SwizzleArray that returns a Tensor with default F-major order:
```
jl.Tensor(storage.levels_descr._obj, tensor._obj)
```

I would like a new `copy_swizzle(dest::SwizzleArray, src::SwizzleArray)` function, which returns a SwizzleArray (or `Tensor(dest::SwizzleArray, src::SwizzleArray)` if it's more coherent).

This would allow me to pass CSC tensor and get a CSR array easily:
```julia
copy_swizzle(swizzle(Dense(SparseList(Element(0))), (2, 1)), csc_swizzle_array)
```
WDYT?

**Comment by willow-ahrens** [comment]
I think in julia you can call copyto

**Comment by mtsokol** [comment]
@willow-ahrens Thank you! With `copyto!` resetting `order` is avoided. But I noticed that `copyto!` from dense to sparse format treats zeros as non-fill-values. How can I avoid it?

```julia
using Finch

arr = [0 1 0; 2 3 0]
tns = Tensor(arr)
sw = swizzle(tns, 1, 2)

copyto!(swizzle(Tensor(Dense(SparseList(Element(0)))), 1, 2), sw)

SwizzleArray (1, 2)
└─ 2×3-Tensor
   └─ Dense [:,1:3]
      ├─ [:, 1]: SparseList (0) [1:2]
      │  ├─ [1]: 0
      │  └─ [2]: 2
      ├─ [:, 2]: SparseList (0) [1:2]
      │  ├─ [1]: 1
      │  └─ [2]: 3
      └─ [:, 3]: SparseList (0) [1:2]
         ├─ [1]: 0
         └─ [2]: 0
```

**Comment by mtsokol** [comment]
I also managed to avoid copying fill-values with `dropfills!` but for `csr` format it fails with:
```
ERROR: Finch.FinchProtocolError("SparseListLevels cannot be updated multiple times")
```

```julia
using Finch

arr = [0 1 0; 2 3 0]
tns = Tensor(arr)
sw = swizzle(tns, 1, 2)

dropfills!(swizzle(Tensor(Dense(SparseList(Element(0)))), 2, 1), sw)
```

**Comment by willow-ahrens** [comment]
note: I have made a fix so that dropfills works like copyto. However, dropfills will always make a copy. You must still check for the cases where you can zero-copy during asarray.
