### ISSUE TITLE
C backend

### ISSUE THREAD

**Issue by willow-ahrens** [willow-ahrens/Finch.jl#63]
Is there a way to get Finch to output C, or perhaps to compile the kernels that Finch generates? Some options include:
1. Transpile Finch kernels from [Julia to C](https://juliacomputing.com/blog/2016/03/j2c-announcement/)
2. Compile Finch kernels into static binaries with [StaticCompiler.jl](https://github.com/tshort/StaticCompiler.jl)
3. Compile a system image of a Julia session with Finch loaded using [PackageCompiler.jl](https://github.com/JuliaLang/PackageCompiler.jl)
4. Write a dedicated C or C++ Finch backend
5. Rewrite Finch itself in C or C++

**Comment by Wimmerer** [comment]
LLVM IR? Something I've been thinking about in the reverse direction. Not sure the feasibility though.

**Comment by willow-ahrens** [comment]
Finch has a C interface (we can call Finch from C). Are you thinking we might lift tensor expressions from regular loops in LLVM IR? Or are you thinking that we might lower directly to llvm ir?

**Comment by Wimmerer** [comment]
I was thinking this:

> Transpile Finch kernels from Julia to C

Might be easier by skipping C altogether. Tooling might not be there though.

**Comment by willow-ahrens** [comment]
I think StaticCompiler might be very close to this? In the same way that Julia GPU compiles type-stable code without allocations, I think StaticCompiler uses the same infrastructure to make binaries? I'm not sure if I'm allowed to call `resize` though.

**Comment by willow-ahrens** [comment]
but you're right that we might be able to get away with adding tooling around the output of code_llvm

**Comment by willow-ahrens** [comment]
This is no longer a priority.
