### ISSUE TITLE
Sparse matrix in multi statement fails without additional defs

### ISSUE THREAD

**Issue by adadima** [willow-ahrens/Finch.jl#68]
I have the following statements:

```
@finch @loop j k begin
  new_frontier[j] <<$or>>= edges[j,k] * frontier_list[($round-1),k] * (old_visited[j] == 0)
  new_visited[j] <<$or>>= (old_visited[j] != 0) * 1 + edges[j,k] * frontier_list[($round-1),k] * (old_visited[j] == 0)
  B[j] += edges[j,k] * frontier_list[($round-1),k] * (old_visited[j] == 0) * old_num_paths[k]
end
```
edges and frontier_list are both CSR, so one example is: 

```
edges = finch_eval("N = 3
edge_matrix = sparse([0 1 1; 1 0 1; 1 0 0])
Finch.Fiber(
  Dense(N,
  SparseList(N, edge_matrix.colptr, edge_matrix.rowval,
  Element{0.0}(edge_matrix.nzval))))");
```
The rest of the vectors are dense and of size N.

It works if I take the 3 statements out of the multi. It also works if I keep the multi but add the following function:

```
function (ctx::LowerJulia)(root::Multi, style::StepperStyle)
  thunk = Expr(:block)
  for body in root.bodies
    push!(thunk.args, quote
      $(contain(ctx) do ctx_2
        (ctx_2)(body)
      end)
    end)
  end
  thunk
end
```

**Comment by willow-ahrens** [comment]
I'm currently working on debugging this. There's a separate issue here related to the performance of your expression.

If you write
```
@finch @loop i @multi begin
  B[i] = A[i]
  C[i] = A[i] * 2
end
```
then Finch emits a loop that merges `A` with itself.

If you instead write
```
@finch @loop i @multi begin
  B[i] = w[]
  C[i] = w[] * 2
end @where w[] = A[i]
```
then finch emits a loop that only iterates over `A`.

There's a case to be made that we should run common subexpression elimination, but it's a separate issue.
