### ISSUE TITLE
On-demand compilation, separate from execution

### ISSUE THREAD

**Issue by adadima** [willow-ahrens/Finch.jl#70]
Would be nice to have a feature in finch that allows you to just compile an expression and get the generated code ( which can then be called from C by passing in input and output tensors as jl_value_t* to ). TACO has something similar in the sense that you can call compile() to get a kernel and then print the kernel to a file or call it in order to actually execute the code. So maybe something like:

`code = @finch_compile @loop i  a[i] = .....`

Obviously there needs to be a way to specify what format the output and input tensors are, so we should discuss that. One way would be to initialize these to dummy/empty versions of the real tensors before doing the @finch_compile. Or specify the types directly to @finch_compile thought the expression might become too intricate.

Happy to chat more about how this would be designed.

**Comment by willow-ahrens** [comment]
In Finch, most of the tensors can be easily initialized as empty. Would it be an okay interface to specify tensors that way?

e.g. one approach for a saxpy would be:

```
jl_value_t saxpy_sparse_kernel = finch_eval(" \n\
function saxpy(s, a, x, y) \n\
  @finch @loop i s[i] += $a * x[i] + y[i] \n\
end\n\
spvec = typeof(@fiber sl(e(0.0)))
magic_compiler(saxpy, (spvec, typeof(Float64), spvec, spvec))
");
```
and then we could call the saxpy_sparse_kernel without incurring compile costs.

Additionally, it would be good to have a `finch_call_direct` function which calls julia methods on fixed types and avoids dispatch overheads.

What do you think?

**Comment by willow-ahrens** [comment]
Or were you asking more for something like

```
@finch_kernel saxpy(s::(@fiber sl(e(0.0))), a::Int, x::(@fiber sl(e(0.0))), y::(@fiber sl(e(0.0)))) =
   @loop i s[i] += $a * x[i] + y[i]
 ```
 
 which returns julia code for the saxpy function with the `@finch` call expanded and replaced with equivalent code?

**Comment by adadima** [comment]
Yes, I think the second version is more like what I had in mind.

**Comment by willow-ahrens** [comment]
Cool! Okay, I think the second thing could currently be roughly implemented as follows:

```
  s = virtualize(:s, typeof(@fiber sl(e(0.0))))
  a = virtualize(:a, Int)
  x = virtualize(:x, typeof(@fiber sl(e(0.0))))
  y = virtualize(:y, typeof(@fiber sl(e(0.0))))
  kernel_code = @finch_program @loop s[i] += $a * x[i] + y[i]
  function_code = quote
    function saxpy(s, a, x, y)
      $kernel_code
    end
  end
return function_code
```

What do you think of this potential interface?

**Comment by adadima** [comment]
Looks good, but maybe there s a way to generalize it to any kernel with any inputs so that a user doesn't have to write this entire block everytime. So maybe calling @finch_compile with s,a,x,y as input and then the loop could under the hood implement what you just wrote above?

**Comment by willow-ahrens** [comment]
I'm not sure what you mean, perhaps an example would help me?

**Comment by adadima** [comment]
I was wondering if it's possible for something like `@finch_kernel saxpy(s::(@fiber d(e(0.0))), a::Int, x::(@fiber d(e(0.0))), y::(@fiber d(e(0.0)))) =
   @loop i s[i] += $a * x[i] + y[i]` to return the kernel as computed above. So then 

`@finch_kernel saxpy(s::type_s, a::type_a, x::type_s, y::type_y) = LOOP ` would be implemented as:

```
  s = virtualize(:s, type_s)
  a = virtualize(:a, type_a)
  x = virtualize(:x, type_x)
  y = virtualize(:y, type+y)
  kernel_code = @finch_program LOOP
  function_code = quote
    function saxpy(s, a, x, y)
      $kernel_code
    end
  end
return function_code
```

**Comment by willow-ahrens** [comment]
Ah I see, yeah just something to reduce boilerplate. This is very possible.

**Comment by willow-ahrens** [comment]
A note on the correct usage of `virtualize`, you'll need to use something like the following:
```
ctx = LowerJulia()
code = contain(ctx) do ctx_2
  s = virtualize(:s, type_s, ctx_2)
  a = virtualize(:a, type_a, ctx_2)
  x = virtualize(:x, type_x, ctx_2)
  y = virtualize(:y, type_y, ctx_2)
  kernel= @finch_program LOOP
  kernel_code = execute(kernel, ctx_2)
  return quote
    function saxpy(s, a, x, y)
      $kernel_code
    end
  end
end
```

**Comment by willow-ahrens** [comment]
The `ctx_2` and `contain` calls allow functions that don't return code to generate code as they do their thing.
