### ISSUE TITLE
More descriptive error messages

### ISSUE THREAD

**Issue by willow-ahrens** [willow-ahrens/Finch.jl#97]
This is a meta issue to record instances where we need better error messages.

A few to get started:

- [x] Array accessed with too many or too few dimensions (the size of the access does not match the dimensionality of the tensor)
- [ ] Tensor type not recognized by Finch

**Comment by kylebd99** [comment]
A few other aspects which could use more descriptive error messages/clearer documentation:

- [ ]  Attempting to use an access protocol which is unsupported by a level format, e.g. using a follow protocol for a SparseList level or using a walk protocol for a Dense level.

Currently, for the following code snippet:

```
DIMENSION_SIZE = 400
t = @fiber(sl(sl((e(0.0)))))
A = copyto!(@fiber(sl(sl(e(0.0)))), sprand(DIMENSION_SIZE, DIMENSION_SIZE, .1))
x = copyto!(@fiber(d(e(0.0))), sprand(DIMENSION_SIZE, .1))
@finch @loop i j t[i, j] += A[i::follow, j] * x[i]
```
It returns the following error:
```
MethodError: no method matching unfurl(::Finch.VirtualFiber{Finch.VirtualSparseListLevel}, ::Finch.LowerJulia, ::Finch.IndexNotation.IndexNode, ::Finch.IndexNotation.Follow, ::Finch.IndexNotation.IndexNode, ::Finch.IndexNotation.IndexNode)
```

- [ ] Attempting to access tensor indices in an order which doesn't match the loop ordering.

For the following code snippet:
```
DIMENSION_SIZE = 400
t = @fiber(d(sl((e(0.0)))))
A = copyto!(@fiber(sl(sl(e(0.0)))), sprand(DIMENSION_SIZE, DIMENSION_SIZE, .1))
x = copyto!(@fiber(sl(sl(e(0.0)))), sprand(DIMENSION_SIZE, DIMENSION_SIZE, .1))
@finch @loop i j t[i, j] += A[i, j] * x[j, i]
```
It returns the following error:
```
MethodError: no method matching combine_style(::Finch.SelectStyle, ::Finch.RunStyle)
```
- [ ] Attempting to use the SparseHash level format. This may just not be available yet, but the test files imply its existence.
The following code:
```
DIMENSION_SIZE = 400
t = @fiber(d(sl((e(0.0)))))
A = copyto!(@fiber(sh(sl(e(0.0)))), sprand(DIMENSION_SIZE, DIMENSION_SIZE, .1))
x = copyto!(@fiber(sl(sl(e(0.0)))), sprand(DIMENSION_SIZE, DIMENSION_SIZE, .1))
@finch @loop j i t[i, j] += A[i, j] * x[i, j]
```
Returns the following error:
```
MethodError: no method matching Finch.SparseHashLevel(::Finch.SparseListLevel{Int64, Int64, Finch.ElementLevel{0.0, Float64}})
```

**Comment by willow-ahrens** [comment]
- [ ] Add dimension mismatch errors and documentation

**Comment by willow-ahrens** [comment]
- [ ] Error on invalid tensor reuse scenarios.

**Comment by willow-ahrens** [comment]
- [ ] To elaborate on the last error, some formats require in-order traversal, we should be able to reliably check this property (even when the format in question is nested inside another more permissive one).

**Comment by willow-ahrens** [comment]
`@finch` macro should spit out the line number when it fails

**Comment by willow-ahrens** [comment]
- [ ] Error when finch is called on non-isbits types

**Comment by willow-ahrens** [comment]
While trying to figure out what kind of errors Finch produces when given non-array arguments:

```
julia> x = zeros(3)
3-element Vector{Float64}:
 0.0
 0.0
 0.0

julia> y = "foo"
"foo"

julia> @finch for i = _ x[i] = y[i] end
(x = [102.0, 111.0, 111.0],)
```

**Comment by willow-ahrens** [comment]
I think that Finch actually errors somewhat gracefully when the tensor type is not supported, by simply stating which array method it didn't implement. I think this issue is safe to close for now, and if anyone finds more cases where they would have liked a better error, please file a new issue!
